[package]
name = "report"
version = "0.4.2"
entrypoint = "report.typ"
authors = "Andrew Benson <abenson+typst@gmail.com>"
license = "Unlicense"
description = "Report format with support for markings"
repository = "https://github.com/abenson/report"
